# Use the official OpenJDK base image

FROM openjdk:11-jre-slim


# Set the working directory in the container

WORKDIR /app


# Copy the executable JAR file into the container at /app

COPY target/HelloWorld.jar /app/HelloWorld.jar


# Command to run the JAR file

CMD ["java", "-jar", "HelloWorld.jar"]